### ISSUE TITLE
error email

### ISSUE THREAD

**Issue by spinaldf** [pluginsGLPI/metabase#13]
Dears, I user glpi 9.2.4 and I have this problem:

**Client error: `POST http://127.0.0.1:3000/api/session` resulted in a `400 Bad Request` response: {"errors":{"email":"value must be a valid email address."}}**

Logs of apache:

**Uncaught Error: Class 'GLPINetwork' not found in /var/www/html/glpi/plugins/metabase/inc/config.class.php:174\nStack trace:\n#0 /var/www/html/glpi/plugins/metabase/inc/config.class.php(35): PluginMetabaseConfig::showForConfig(Object(Config), '')\n#1 /var/www/html/glpi/inc/commonglpi.class.php(482): PluginMetabaseConfig::displayTabContentForItem(Object(Config), '1', '')\n#2 /var/www/html/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Config), 'PluginMetabaseC...', '', Array)\n#3 {main}\n  thrown in /var/www/html/glpi/plugins/metabase/inc/config.class.php on line 174, referer: http://my-server.com/glpi/front/config.form.php?forcetab=PluginMetabaseConfig$1**

I use postfix, I tried send email on text mode and work, also metabase send email, work too.

Any suggestion?

**Comment by spinaldf** [comment]
My solution, I update for last version of metabase and doesn't show this error.
