### ISSUE TITLE
0 =>	No auto-generated GLPI database found

### ISSUE THREAD

**Issue by spinaldf** [pluginsGLPI/metabase#14]
Dears,
           I have new error: "0 =>	No auto-generated GLPI database found"

![metabase](https://user-images.githubusercontent.com/42477982/63536881-e717d180-c4ea-11e9-88a1-caed9508eba1.png)

Any suggestion?

**Comment by GuilhermeSaravy** [comment]
> This problem is only with version 9.2.x
> 
> I look this error on log:
> ################################################
> PHP Fatal error: Uncaught Error: Class 'GLPINetwork' not found in /var/www/html/glpi/plugins/metabase/inc/config.class.php:174\nStack trace:\n#0 /var/www/html/glpi/plugins/metabase/inc/config.class.php(35): PluginMetabaseConfig::showForConfig(Object(Config), '')\n#1 /var/www/html/glpi/inc/commonglpi.class.php(482): PluginMetabaseConfig::displayTabContentForItem(Object(Config), '1', '')\n#2 /var/www/html/glpi/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Config), 'PluginMetabaseC...', '', Array)\n#3 {main}\n thrown in /var/www/html/glpi/plugins/metabase/inc/config.class.php on line 174, referer: http://xsara.redecamara.camara.gov.br/glpi/front/config.form.php?forcetab=PluginMetabaseConfig$1
> ################################################
> 
> My solution:
> 
> I copy file of version 9.3.3 of glpi to glpi 9.2.x
> /var/www/html/glpi933/inc/glpinetwork.class.php /var/www/html/glpi/inc/glpinetwork.class.php

Thanks, it really works here.

**Comment by msvanegasg17** [comment]
con la versión 9.5.4 con la versión del plugin 1.2.2 de metabase y el servidor de metabase 0.38.1, en el servidor de metabase no he creado la instancia para la base de datos del GLPI
![Captura de pantalla 2021-03-04 133021](https://user-images.githubusercontent.com/77513235/110011780-cdfdfc80-7ced-11eb-96e1-efa29182a890.png)
